import type { User, Lugar, Evento, Oportunidade, Projeto } from "./types";

export const mockUsers: User[] = [
  {
    id: "1",
    nome: "Maria Clara Silva",
    email: "maria.clara@email.com",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop",
    roles: ["artista", "educador"],
    areasAtuacao: ["musica", "danca", "cultura_popular"],
    biografia: "Artista multidisciplinar com 15 anos de experiência em projetos culturais comunitários. Dedico minha vida à preservação e divulgação da cultura popular brasileira.",
    oQueFaz: "Professora de dança e música tradicional, produtora de eventos culturais.",
    cidade: "Teresina",
    estado: "PI",
    telefone: "(86) 99999-1234",
    website: "https://mariaclara.art.br",
    redesSociais: {
      instagram: "@mariaclara.art",
      facebook: "mariaclarasilva",
    },
    isBrasileiro: true,
    aceitouTermos: true,
    createdAt: "2024-01-15",
    tipoAtuacao: "individual",
  },
  {
    id: "2",
    nome: "Coletivo Raízes do Piauí",
    email: "raizesdopiaui@email.com",
    avatar: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=150&h=150&fit=crop",
    roles: ["produtor_cultural", "promotor_eventos"],
    areasAtuacao: ["cultura_popular", "musica", "artesanato", "gastronomia"],
    biografia: "Coletivo cultural fundado em 2010, dedicado à promoção e valorização da cultura piauiense através de eventos, oficinas e projetos educacionais.",
    oQueFaz: "Organização de festivais culturais, oficinas de artesanato e gastronomia regional.",
    cidade: "Parnaíba",
    estado: "PI",
    isBrasileiro: true,
    aceitouTermos: true,
    createdAt: "2023-06-20",
    tipoAtuacao: "coletivo",
  },
  {
    id: "3",
    nome: "João Pedro Mendes",
    email: "joaopedro@email.com",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop",
    roles: ["empresario", "dono_estabelecimento"],
    areasAtuacao: ["musica", "audiovisual"],
    biografia: "Empresário do ramo cultural, proprietário do principal bar com música ao vivo da cidade.",
    oQueFaz: "Gestão de casa de shows e produção de eventos musicais.",
    cidade: "Teresina",
    estado: "PI",
    telefone: "(86) 98888-5678",
    isBrasileiro: true,
    aceitouTermos: true,
    createdAt: "2024-02-10",
    tipoAtuacao: "individual",
  },
  {
    id: "4",
    nome: "Ana Beatriz Costa",
    email: "anabeatriz@email.com",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop",
    roles: ["artista", "pesquisador"],
    areasAtuacao: ["artes_visuais", "patrimonio_cultural"],
    biografia: "Artista visual e pesquisadora de arte popular nordestina. Mestre em Artes pela UFPI.",
    oQueFaz: "Criação de obras de arte, pesquisa acadêmica e curadoria de exposições.",
    cidade: "Picos",
    estado: "PI",
    redesSociais: {
      instagram: "@anabeatriz.arte",
    },
    isBrasileiro: true,
    aceitouTermos: true,
    createdAt: "2023-11-05",
    tipoAtuacao: "individual",
  },
  {
    id: "5",
    nome: "Teatro Popular do Nordeste",
    email: "teatropopular@email.com",
    avatar: "https://images.unsplash.com/photo-1503095396549-807759245b35?w=150&h=150&fit=crop",
    roles: ["produtor_cultural", "artista"],
    areasAtuacao: ["teatro", "cultura_popular", "literatura"],
    biografia: "Grupo de teatro fundado em 1995, com mais de 50 espetáculos produzidos e apresentações em todo o Brasil.",
    oQueFaz: "Produção de espetáculos teatrais, oficinas de formação de atores.",
    cidade: "Teresina",
    estado: "PI",
    website: "https://teatropopulardone.com.br",
    isBrasileiro: true,
    aceitouTermos: true,
    createdAt: "2023-03-12",
    tipoAtuacao: "coletivo",
  },
];

export const mockLugares: Lugar[] = [
  {
    id: "1",
    nome: "Praça da Bandeira",
    tipo: "praca",
    descricao: "Principal praça do centro histórico de Teresina, palco de diversos eventos culturais ao longo do ano. Local de encontro de artistas de rua e ponto tradicional de manifestações culturais.",
    endereco: {
      logradouro: "Praça da Bandeira",
      numero: "S/N",
      bairro: "Centro",
      cidade: "Teresina",
      estado: "PI",
      cep: "64000-000",
    },
    coordenadas: {
      lat: -5.0892,
      lng: -42.8019,
    },
    acessibilidade: true,
    areasAtuacao: ["musica", "cultura_popular", "artesanato"],
    imagem: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=800&h=500&fit=crop",
    createdById: "1",
    createdAt: "2024-01-20",
    isOficial: true,
  },
  {
    id: "2",
    nome: "Teatro 4 de Setembro",
    tipo: "teatro",
    descricao: "O Teatro 4 de Setembro é o principal teatro de Teresina, com capacidade para 800 pessoas. Inaugurado em 1894, é patrimônio histórico e cultural do Piauí.",
    endereco: {
      logradouro: "Rua Areolino de Abreu",
      numero: "300",
      bairro: "Centro",
      cidade: "Teresina",
      estado: "PI",
      cep: "64000-080",
    },
    coordenadas: {
      lat: -5.0887,
      lng: -42.8041,
    },
    acessibilidade: true,
    areasAtuacao: ["teatro", "musica", "danca"],
    imagem: "https://images.unsplash.com/photo-1503095396549-807759245b35?w=800&h=500&fit=crop",
    telefone: "(86) 3221-1234",
    email: "teatro4setembro@cultura.pi.gov.br",
    horarioFuncionamento: "Ter-Dom: 14h às 22h",
    createdById: "2",
    createdAt: "2023-08-15",
    isOficial: true,
  },
  {
    id: "3",
    nome: "Casa da Cultura de Parnaíba",
    tipo: "centro_cultural",
    descricao: "Centro cultural que preserva e divulga a história e cultura da região do Delta do Parnaíba. Oferece exposições permanentes e temporárias, além de oficinas culturais.",
    endereco: {
      logradouro: "Avenida Presidente Getúlio Vargas",
      numero: "1400",
      bairro: "Centro",
      cidade: "Parnaíba",
      estado: "PI",
      cep: "64200-100",
    },
    coordenadas: {
      lat: -2.9055,
      lng: -41.7768,
    },
    acessibilidade: false,
    areasAtuacao: ["patrimonio_cultural", "artes_visuais", "artesanato"],
    imagem: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&h=500&fit=crop",
    telefone: "(86) 3322-5678",
    horarioFuncionamento: "Ter-Sáb: 9h às 17h",
    createdById: "1",
    createdAt: "2024-02-01",
    isOficial: false,
  },
  {
    id: "4",
    nome: "Museu do Piauí",
    tipo: "museu",
    descricao: "O Museu do Piauí está instalado no antigo Palácio do Governo, um dos prédios históricos mais importantes do estado. Possui acervo com peças de arqueologia, etnografia e história regional.",
    endereco: {
      logradouro: "Praça Marechal Deodoro da Fonseca",
      numero: "700",
      bairro: "Centro",
      cidade: "Teresina",
      estado: "PI",
      cep: "64000-160",
    },
    coordenadas: {
      lat: -5.0890,
      lng: -42.8055,
    },
    acessibilidade: true,
    areasAtuacao: ["patrimonio_cultural", "artes_visuais"],
    imagem: "https://images.unsplash.com/photo-1564399579883-451a5d44ec08?w=800&h=500&fit=crop",
    telefone: "(86) 3221-9876",
    email: "museudopiaui@cultura.pi.gov.br",
    horarioFuncionamento: "Ter-Sex: 8h às 18h, Sáb: 8h às 12h",
    createdById: "3",
    createdAt: "2023-05-10",
    isOficial: true,
  },
  {
    id: "5",
    nome: "Bar do Blues",
    tipo: "bar_cultural",
    descricao: "Casa de shows especializada em blues, rock e MPB. Ambiente intimista com apresentações ao vivo todas as sextas e sábados.",
    endereco: {
      logradouro: "Rua Simplício Mendes",
      numero: "1850",
      bairro: "Fátima",
      cidade: "Teresina",
      estado: "PI",
      cep: "64049-000",
    },
    coordenadas: {
      lat: -5.0755,
      lng: -42.7890,
    },
    acessibilidade: false,
    areasAtuacao: ["musica"],
    imagem: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800&h=500&fit=crop",
    telefone: "(86) 99777-1234",
    horarioFuncionamento: "Qui-Sáb: 19h às 02h",
    createdById: "3",
    createdAt: "2024-01-05",
    isOficial: false,
  },
];

export const mockEventos: Evento[] = [
  {
    id: "1",
    nome: "Festival de Inverno de Teresina",
    descricao: "O maior festival de música e arte do Piauí, com apresentações de artistas locais e nacionais. Uma semana inteira de programação cultural diversificada com shows, exposições, oficinas e muito mais.",
    dataInicio: "2026-07-25",
    dataFim: "2026-07-31",
    horario: "18:00",
    lugarId: "1",
    classificacao: "livre",
    entrada: "gratuito",
    areasAtuacao: ["musica", "danca", "artes_visuais", "gastronomia"],
    tags: ["festival", "música", "arte", "cultura"],
    imagem: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=500&fit=crop",
    createdById: "2",
    createdAt: "2024-03-01",
    isOficial: true,
  },
  {
    id: "2",
    nome: "Espetáculo: Raízes do Sertão",
    descricao: "Espetáculo de dança contemporânea que mistura elementos da cultura nordestina com técnicas modernas. Uma viagem emocionante pelas tradições do sertão piauiense.",
    dataInicio: "2026-05-15",
    horario: "20:00",
    lugarId: "2",
    classificacao: "livre",
    entrada: "pago",
    preco: 40,
    areasAtuacao: ["danca", "musica", "cultura_popular"],
    tags: ["dança", "cultura nordestina", "espetáculo"],
    imagem: "https://images.unsplash.com/photo-1508700929628-666bc8bd84ea?w=800&h=500&fit=crop",
    createdById: "5",
    createdAt: "2024-02-20",
    isOficial: true,
  },
  {
    id: "3",
    nome: "Feira de Artesanato do Delta",
    descricao: "Exposição e venda de artesanato regional do Delta do Parnaíba. Encontre peças únicas feitas por artesãos locais, incluindo cerâmica, bordados, esculturas em madeira e muito mais.",
    dataInicio: "2026-05-20",
    dataFim: "2026-05-22",
    horario: "09:00",
    lugarId: "3",
    classificacao: "livre",
    entrada: "gratuito",
    areasAtuacao: ["artesanato", "cultura_popular"],
    tags: ["artesanato", "feira", "cultura regional"],
    imagem: "https://images.unsplash.com/photo-1513519245088-0e12902e35ca?w=800&h=500&fit=crop",
    createdById: "1",
    createdAt: "2024-03-05",
    isOficial: false,
  },
  {
    id: "4",
    nome: "Noite de Blues - Edição Especial",
    descricao: "Uma noite especial com as melhores bandas de blues da cidade. Repertório que vai dos clássicos americanos ao blues brasileiro. Não perca!",
    dataInicio: "2026-04-26",
    horario: "21:00",
    lugarId: "5",
    classificacao: "18",
    entrada: "pago",
    preco: 25,
    areasAtuacao: ["musica"],
    tags: ["blues", "música ao vivo", "show"],
    imagem: "https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800&h=500&fit=crop",
    createdById: "3",
    createdAt: "2024-03-10",
    isOficial: false,
  },
  {
    id: "5",
    nome: "Exposição: Arte Popular Piauiense",
    descricao: "Mostra coletiva com obras de artistas populares do Piauí, apresentando técnicas tradicionais de pintura, escultura e cerâmica. Curadoria de Ana Beatriz Costa.",
    dataInicio: "2026-06-01",
    dataFim: "2026-08-31",
    horario: "08:00",
    lugarId: "4",
    classificacao: "livre",
    entrada: "gratuito",
    areasAtuacao: ["artes_visuais", "patrimonio_cultural"],
    tags: ["exposição", "arte popular", "artistas locais"],
    imagem: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=800&h=500&fit=crop",
    createdById: "4",
    createdAt: "2024-02-28",
    isOficial: true,
  },
  {
    id: "6",
    nome: "Oficina de Percussão Nordestina",
    descricao: "Aprenda os ritmos tradicionais do Nordeste brasileiro! Oficina aberta para todos os níveis, do iniciante ao avançado. Instrumentos fornecidos pelo evento.",
    dataInicio: "2026-05-10",
    horario: "14:00",
    lugarId: "3",
    classificacao: "10",
    entrada: "gratuito",
    areasAtuacao: ["musica", "cultura_popular"],
    tags: ["oficina", "percussão", "música nordestina"],
    imagem: "https://images.unsplash.com/photo-1519892300165-cb5542fb47c7?w=800&h=500&fit=crop",
    createdById: "1",
    createdAt: "2024-03-08",
    isOficial: false,
  },
];

// Função para popular eventos com dados dos lugares
export function getEventosComLugares(): Evento[] {
  return mockEventos.map((evento) => ({
    ...evento,
    lugar: mockLugares.find((lugar) => lugar.id === evento.lugarId),
  }));
}

export const mockOportunidades: Oportunidade[] = [
  {
    id: "1",
    nome: "Edital de Fomento à Cultura 2026",
    tipo: "edital",
    descricao: "Edital de fomento para projetos culturais que valorizem a identidade cultural do Piauí. Serão selecionados até 50 projetos nas mais diversas linguagens artísticas.",
    dataInscricaoInicio: "2026-03-01",
    dataInscricaoFim: "2026-05-30",
    areasInteresse: ["musica", "danca", "teatro", "artes_visuais", "literatura", "audiovisual"],
    requisitos: "Pessoa física ou jurídica com atuação comprovada na área cultural há pelo menos 2 anos.",
    valorPremio: 30000,
    link: "https://cultura.pi.gov.br/edital-fomento-2026",
    isOficial: true,
    createdById: "1",
    createdAt: "2026-02-15",
  },
  {
    id: "2",
    nome: "Prêmio Artistas Revelação",
    tipo: "premio",
    descricao: "Premiação para novos talentos da música piauiense. Artistas com até 5 anos de carreira podem se inscrever e concorrer a prêmios em dinheiro e gravação de álbum.",
    dataInscricaoInicio: "2026-04-01",
    dataInscricaoFim: "2026-06-15",
    areasInteresse: ["musica"],
    requisitos: "Artistas residentes no Piauí com até 5 anos de carreira musical.",
    valorPremio: 15000,
    isOficial: true,
    createdById: "2",
    createdAt: "2026-03-10",
  },
  {
    id: "3",
    nome: "Oficina de Cerâmica Tradicional",
    tipo: "oficina",
    descricao: "Oficina gratuita de cerâmica com técnicas tradicionais do sertão nordestino. Vagas limitadas para 20 participantes.",
    dataInscricaoInicio: "2026-04-10",
    dataInscricaoFim: "2026-04-25",
    areasInteresse: ["artesanato", "cultura_popular"],
    requisitos: "Maiores de 16 anos com interesse em artesanato.",
    isOficial: false,
    createdById: "1",
    createdAt: "2026-03-20",
  },
  {
    id: "4",
    nome: "Concurso de Dramaturgia Nordestina",
    tipo: "concurso",
    descricao: "Concurso para textos teatrais inéditos que abordem temas relacionados à cultura e história do Nordeste brasileiro.",
    dataInscricaoInicio: "2026-01-15",
    dataInscricaoFim: "2026-03-15",
    areasInteresse: ["teatro", "literatura"],
    requisitos: "Dramaturgos brasileiros, sem restrição de idade ou região.",
    valorPremio: 10000,
    isOficial: true,
    createdById: "5",
    createdAt: "2025-12-01",
  },
  {
    id: "5",
    nome: "Residência Artística Casa das Artes",
    tipo: "residencia",
    descricao: "Programa de residência artística de 3 meses para artistas visuais desenvolverem projetos autorais. Inclui hospedagem, alimentação e ajuda de custo.",
    dataInscricaoInicio: "2026-05-01",
    dataInscricaoFim: "2026-07-31",
    areasInteresse: ["artes_visuais"],
    requisitos: "Artistas visuais com portfólio comprovado e projeto artístico definido.",
    valorPremio: 5000,
    link: "https://casadasartes.org.br/residencia",
    isOficial: false,
    createdById: "4",
    createdAt: "2026-04-01",
  },
];

export const mockProjetos: Projeto[] = [
  {
    id: "1",
    nome: "Encontro Pedagógico Ensinando com a Capoeira",
    tipo: "intercambio_cultural",
    descricao: "O esporte consolida-se hoje como uma prática privilegiada e valorizada como meio de educação, merecendo a preocupação de todos os atores da sociedade. O projeto promove intercâmbio cultural através da capoeira como ferramenta educacional.",
    dataInicio: "2026-03-01",
    dataFim: "2026-12-15",
    areasAtuacao: ["cultura_popular", "danca", "musica"],
    responsavel: "Associação de Capoeira do Piauí",
    parceiros: ["Secretaria de Educação", "UFPI"],
    isOficial: true,
    imagem: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=500&fit=crop",
    createdById: "2",
    createdAt: "2026-01-15",
  },
  {
    id: "2",
    nome: "Projeto Auí - Bordados da Caatinga",
    tipo: "oficina",
    descricao: "Projeto desenvolvido pelo Sebrae Piauí com consultoria da marca de renome nacional Catarina Mina para desenvolvimento de coleção de bordados com as mulheres bordadeiras da região.",
    dataInicio: "2026-02-01",
    dataFim: "2026-08-30",
    areasAtuacao: ["artesanato", "cultura_popular"],
    responsavel: "Sebrae Piauí",
    parceiros: ["Catarina Mina", "Associação das Bordadeiras"],
    isOficial: true,
    imagem: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=500&fit=crop",
    createdById: "1",
    createdAt: "2026-01-20",
  },
  {
    id: "3",
    nome: "Festival de Cinema do Piauí",
    tipo: "festival",
    descricao: "Festival anual de cinema que exibe produções audiovisuais locais, regionais e nacionais, com foco em obras que retratam a diversidade cultural brasileira.",
    dataInicio: "2026-09-15",
    dataFim: "2026-09-22",
    areasAtuacao: ["audiovisual"],
    responsavel: "Associação de Cineastas do Piauí",
    parceiros: ["Governo do Estado", "Ancine", "UFPI"],
    isOficial: true,
    imagem: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&h=500&fit=crop",
    createdById: "3",
    createdAt: "2025-11-01",
  },
  {
    id: "4",
    nome: "Memórias do Sertão - Documentação Oral",
    tipo: "pesquisa",
    descricao: "Projeto de pesquisa e documentação de histórias orais de comunidades tradicionais do sertão piauiense, preservando memórias e saberes ancestrais.",
    dataInicio: "2026-01-01",
    areasAtuacao: ["patrimonio_cultural", "literatura"],
    responsavel: "Núcleo de Pesquisa Cultural - UFPI",
    parceiros: ["IPHAN", "Fundação Cultural do Piauí"],
    isOficial: true,
    imagem: "https://images.unsplash.com/photo-1516541196182-6bdb0516ed27?w=800&h=500&fit=crop",
    createdById: "4",
    createdAt: "2025-10-15",
  },
  {
    id: "5",
    nome: "Escola de Artes Cênicas",
    tipo: "formacao",
    descricao: "Programa de formação em artes cênicas para jovens de 14 a 25 anos, oferecendo aulas de teatro, expressão corporal, cenografia e produção cultural.",
    dataInicio: "2026-03-01",
    dataFim: "2026-11-30",
    areasAtuacao: ["teatro", "danca"],
    responsavel: "Teatro Popular do Nordeste",
    parceiros: ["Secretaria de Cultura", "Instituto de Artes"],
    isOficial: false,
    imagem: "https://images.unsplash.com/photo-1503095396549-807759245b35?w=800&h=500&fit=crop",
    createdById: "5",
    createdAt: "2026-02-01",
  },
];

// Função para calcular status da oportunidade
export function getStatusOportunidade(oportunidade: Oportunidade): "aberta" | "encerrada" | "futura" {
  const hoje = new Date();
  const inicio = new Date(oportunidade.dataInscricaoInicio);
  const fim = new Date(oportunidade.dataInscricaoFim);
  
  if (hoje < inicio) return "futura";
  if (hoje > fim) return "encerrada";
  return "aberta";
}
